# Generated by Django 4.1 on 2022-09-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hit',
        ),
    ]
