# Generated by Django 4.1 on 2022-09-14 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_nickname_user_username_user_age_user_city_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nationality',
            fields=[
                ('country_idx', models.IntegerField(primary_key=True, serialize=False)),
                ('country_code', models.CharField(max_length=10)),
                ('country_dcode', models.CharField(max_length=10)),
                ('country_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.ForeignKey(default='Korea', on_delete=django.db.models.deletion.CASCADE, related_name='user_nationality', to='user.nationality'),
        ),
    ]
