# Generated by Django 4.1 on 2022-09-14 23:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 날짜')),
                ('pay_state', models.PositiveIntegerField(choices=[(0, '결제취소'), (1, '결제완료')], verbose_name='결제 상태')),
                ('delivery_state', models.PositiveIntegerField(choices=[(0, '배송준비중'), (1, '배송중'), (2, '배송완료')], verbose_name='배송 상태')),
                ('quantity', models.IntegerField(default=1, verbose_name='주문수량')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='정가')),
                ('saled_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='할인가')),
                ('delivery_cost', models.DecimalField(decimal_places=2, default=1200, max_digits=10, verbose_name='배송비')),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='최종결제액')),
                ('buyr_city', models.CharField(default='', max_length=100, verbose_name='도시')),
                ('buyr_country', models.CharField(default='', max_length=30, verbose_name='국가코드')),
                ('buyr_zipx', models.CharField(default='', max_length=30, verbose_name='우편번호')),
                ('vccode', models.IntegerField(default=0, verbose_name='국가번호')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-order_date',),
            },
        ),
    ]
