# Generated by Django 4.1 on 2022-09-14 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('pay_state', models.CharField(default='', max_length=20, verbose_name='결제상태')),
                ('quantity', models.IntegerField(default=1, verbose_name='주문수량')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='결제금액')),
                ('buyr_city', models.CharField(default='', max_length=100, verbose_name='도시')),
                ('buyr_country', models.CharField(default='', max_length=30, verbose_name='국가코드')),
                ('buyr_zipx', models.CharField(default='', max_length=30, verbose_name='우편번호')),
                ('vccode', models.IntegerField(default=0, verbose_name='국가번호')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-order_date',),
            },
        ),
    ]
