# Generated by Django 4.1 on 2023-02-22 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='coupon.coupon'),
            preserve_default=False,
        ),
    ]
