# Generated by Django 4.1 on 2022-09-15 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buyr_country',
            field=models.CharField(default='', max_length=100, verbose_name='국가코드'),
        ),
    ]
