# Generated by Django 4.1 on 2022-09-15 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_buyr_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=100, verbose_name='국가이름')),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(72)], verbose_name='주문수량')),
                ('cost', models.DecimalField(decimal_places=2, default=1200, max_digits=10, verbose_name='배송비')),
            ],
        ),
        migrations.AlterField(
            model_name='order',
            name='saled_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='할인금액'),
        ),
    ]
