# Generated by Django 4.1 on 2023-02-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupontype',
            name='dc_type',
            field=models.CharField(choices=[(0, '배송비 할인'), (1, '퍼센트(%) 할인'), (2, '정액 할인(KRW)'), (3, '정액 할인(USD)')], max_length=16, verbose_name='타입(할인종류)'),
        ),
    ]
